# fly.toml file generated for bytebot-dev on 2023-03-26T13:39:00-04:00

app = "bytebot-dev"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[env]

[experimental]
auto_rollback = true

[deploy]
strategy = "canary"
