name: 'Create Release and Update Changelog'
on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/') # only run on tags
    runs-on: ubuntu-latest
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create Release
        uses: softprops/action-gh-release@v0.1.14