name: PR Check
on:
  pull_request:

jobs:
  go-test:
    strategy:
      matrix:
        go-version:
        - 1.14
        - 1.15
        - 1.16
        - 1.17
        - 1.18
        - 1.19
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Test with Go ${{ matrix.go-version }}
      run: go test -v ./...
    